### ISSUE TITLE
Send message to specific channel & elegant way to get channel from cache

### ISSUE THREAD

**Issue by d-513** [Skillz4Killz/gapi#2]
rn it seems that theres no way to just grab the channel by ID and send a message to it. Used client.channels and awaited client.teams.myTeam.fetchChannels tho it doesnt seem theres an option to send a message to one

**Comment by d-513** [comment]
hacky solution request manager.sendMessage

**Comment by Skillz4Killz** [comment]
Update:

@dada513 I've been working on this last few days. I realized how complicated this is as i want to try to do the Channel classes right which channel type allows sending messages and which dont and much more. But there is so much complexities around it so bare with me a bit please but i promise a good solution will come for this

**Comment by d-513** [comment]
> Update:
> 
> 
> 
> @dada513 I've been working on this last few days. I realized how complicated this is as i want to try to do the Channel classes right which channel type allows sending messages and which dont and much more. But there is so much complexities around it so bare with me a bit please but i promise a good solution will come for this

Sure, I've got it working using a workaround in the request manager so take your time
